In [1]:
import numpy as np
import pandas as pd
import wrds
db = wrds.Connection()

Enter your WRDS username [sprth]:ilaukikt
Enter your password:········
WRDS recommends setting up a .pgpass file.
You can find more info here:
https://www.postgresql.org/docs/9.5/static/libpq-pgpass.html.
Loading library list...
Done

In [2]:
data1 = db.raw_sql("SELECT * FROM compa.CO_AFND1 WHERE DATE(datadate) >= '2012-01-31'")
data2 = db.raw_sql("SELECT * FROM compa.CO_AFND2 WHERE DATE(datadate) >= '2012-01-31'")
companies = db.raw_sql('SELECT conm,gvkey,cik FROM compa.company')

In [16]:
data1.info(), data2.info()
companies.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119743 entries, 0 to 119742
Columns: 539 entries, gvkey to datadate
dtypes: datetime64[ns](1), float64(449), object(89)
memory usage: 492.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104592 entries, 0 to 104591
Columns: 468 entries, gvkey to datadate
dtypes: datetime64[ns](1), float64(395), object(72)
memory usage: 373.5+ MB

                      conm   gvkey         cik
0    A & E PLASTIK PAK INC  001000        None
1  A & M FOOD SERVICES INC  001001  0000723576
2                 AAI CORP  001002  0000001745
3    A.A. IMPORTING CO INC  001003  0000730052
4                 AAR CORP  001004  0000001750

In [55]:
def data_frame(df_func):
    df_func['datadate'] = df_func['datadate'].apply(lambda x  : pd.to_datetime(x).date())
    return (df_func)
df1 = data_frame(data1)
df2 = data_frame(data2)

In [56]:
df2

,gvkey,indfmt,datafmt,consol,popsrc,mib,mibn,mibt,mic,mii,...,xstfo,xstfws,xt,xuw,xuwli,xuwnli,xuwoi,xuwrei,xuwti,datadate
0,001004,INDL,STD,C,D,0.0,1.373,1.373,None,0.306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-05-31
1,001004,INDL,STD,C,D,0.0,0.900,0.900,None,0.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-05-31
2,001004,INDL,STD,C,D,0.0,1.200,1.200,None,0.300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-05-31
3,001004,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-05-31
4,001004,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-31
5,001004,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-31
6,001004,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-05-31
7,001004,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-05-31
8,001004,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-05-31
9,001004,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-05-31
10,001004,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31
11,001004,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31
12,001718,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-06-30
13,001045,INDL,STD,C,D,0.0,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
14,001045,INDL,STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31
15,001045,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31
16,001045,INDL,STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-12-31
17,001045,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-12-31
18,001045,INDL,STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-31
19,001045,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-31
20,001045,INDL,STD,C,D,0.0,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
21,001045,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
22,001045,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
23,001045,INDL,STD,C,D,0.0,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
24,001045,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
25,001050,INDL,STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31
26,001050,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31
27,001050,INDL,STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-12-31
28,001050,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-12-31
29,001050,INDL,STD,C,D,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104562,318970,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104563,319507,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-31
104564,319507,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-31
104565,319507,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
104566,319507,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
104567,319507,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104568,319507,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104569,319507,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104570,319507,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104571,324684,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104572,324684,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104573,324684,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104574,324684,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104575,326502,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
104576,326502,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
104577,326502,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104578,326502,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104579,326502,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104580,326502,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104581,326688,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-12-31
104582,326688,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-31
104583,326688,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104584,326688,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104585,326688,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104586,326688,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104587,327451,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-31
104588,327451,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104589,327451,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31
104590,327451,INDL,STD,C,D,0.0,0.000,0.000,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31
104591,327451,INDL,SUMM_STD,C,D,NaN,NaN,NaN,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31

In [61]:
# getting company name ,gvkey and cik indentifiers
compn_name = input('Enter name of the company(full listed name in capital): ')
# example msft = MICROSOFT CORP
comp = companies.loc[companies['conm'] == compn_name ]
display(comp['gvkey'].values[0])

SyntaxError: invalid syntax (<ipython-input-61-6115bf8b8bf5>, line 5)

In [67]:
_bs1 = df1.loc[df1['gvkey'] == comp['gvkey'].values[0] and df1[data.fmt]].set_index('datadate').sort_index().transpose()
_bs2 = df2.loc[df2['gvkey'] == comp['gvkey'].values[0]].set_index('datadate').sort_index().transpose()

In [68]:
comp_fs = pd.concat([_bs1,_bs2])
comp_fs.loc

datadate,2012-06-30,2012-06-30,2013-06-30,2013-06-30,2014-06-30,2014-06-30,2015-06-30,2015-06-30,2016-06-30,2016-06-30,2017-06-30,2017-06-30,2018-06-30,2018-06-30
gvkey,012141,012141,012141,012141,012141,012141,012141,012141,012141,012141,012141,012141,012141,012141
indfmt,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL,INDL
datafmt,STD,SUMM_STD,STD,SUMM_STD,STD,SUMM_STD,STD,SUMM_STD,STD,SUMM_STD,STD,SUMM_STD,STD,SUMM_STD
consol,C,C,C,C,C,C,C,C,C,C,C,C,C,C
popsrc,D,D,D,D,D,D,D,D,D,D,D,D,D,D
acchg,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
accli,None,None,None,None,None,None,None,None,None,None,None,None,None,None
acco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
accrt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acdo,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
aco,5127,NaN,5020,NaN,6333,NaN,7376,NaN,5892,NaN,4897,NaN,6751,NaN
acodo,5127,NaN,5020,NaN,6333,NaN,7376,NaN,5892,NaN,4897,NaN,6751,NaN
acofs,None,None,None,None,None,None,None,None,None,None,None,None,None,None
acominc,1422,NaN,1743,NaN,3708,NaN,2522,NaN,1537,NaN,431,NaN,-2187,NaN
acox,5127,NaN,5020,NaN,6333,NaN,7376,NaN,5892,NaN,4897,NaN,6751,NaN
acoxar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acoxfs,None,None,None,None,None,None,None,None,None,None,None,None,None,None
acqao,NaN,NaN,NaN,NaN,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acqcshi,NaN,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
acqdisn,None,None,None,None,None,None,None,None,None,None,None,None,None,None
acqdiso,None,None,None,None,None,None,None,None,None,None,None,None,None,None
acqgdwl,7198,NaN,937,NaN,5458,NaN,1800,NaN,NaN,NaN,16803,NaN,NaN,NaN
acqic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acqintan,1648,NaN,178,NaN,4509,NaN,928,NaN,NaN,NaN,7887,NaN,NaN,NaN
acqinvt,NaN,NaN,NaN,NaN,544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acqlntal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acqniintc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acqppe,NaN,NaN,NaN,NaN,981,NaN,NaN,NaN,NaN,NaN,1529,NaN,NaN,NaN
acqsc,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,NaN,2268,NaN,NaN,NaN
act,85084,NaN,101466,NaN,114246,NaN,124712,NaN,139660,NaN,159851,NaN,169662,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xnbi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xnf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xnins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xnitb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xobd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xoi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xopr,43009,NaN,47013,NaN,54702,NaN,60008,NaN,58150,NaN,59518,NaN,65402,NaN
xoprar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xopro,None,None,None,None,None,None,None,None,None,None,None,None,None,None
xoptd,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xopteps,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xpp,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
xppfs,None,None,None,None,None,None,None,None,None,None,None,None,None,None
xpr,373,NaN,393,NaN,420,NaN,454,NaN,549,NaN,734,NaN,807,NaN
xrd,9811,NaN,10411,NaN,11381,NaN,12046,NaN,11988,NaN,13037,NaN,14726,NaN
xrdp,9043,NaN,9811,NaN,10411,NaN,11381,NaN,12046,NaN,11988,NaN,13037,NaN
xrent,639,NaN,711,NaN,874,NaN,989,NaN,1000,NaN,1300,NaN,1585,NaN
xs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xsga,28237,NaN,30103,29967,32013,31869,32370,32370,31248,31186,33057,32979,36949,36949
xstf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xstfo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xstfws,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xuw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xuwli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xuwnli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xuwoi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xuwrei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xuwti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
_bs1

,gvkey,indfmt,datafmt,consol,popsrc,acchg,accli,acco,accrt,acdo,...,lrv,ls,lse,lst,lt,ltdch,ltdlch,ltlo,lul3,datadate
14853,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,121271.0,NaN,54908.0,None,None,None,0.0,2012-06-30
14854,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2012-06-30
14855,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,142431.0,NaN,63487.0,None,None,None,0.0,2013-06-30
14856,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2013-06-30
14857,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,172384.0,NaN,82600.0,None,None,None,126.0,2014-06-30
14858,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2014-06-30
14859,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,176223.0,NaN,96140.0,None,None,None,54.0,2015-06-30
14860,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2015-06-30
14861,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,193694.0,NaN,121697.0,None,None,None,0.0,2016-06-30
14862,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2016-06-30
14863,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,241086.0,NaN,168692.0,None,None,None,39.0,2017-06-30
14864,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2017-06-30
14865,012141,INDL,STD,C,D,0.0,None,NaN,NaN,0.0,...,NaN,NaN,258848.0,NaN,176130.0,None,None,None,0.0,2018-06-30
14866,012141,INDL,SUMM_STD,C,D,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,2018-06-30